New structure

diff --git a/install b/install
--- a/install
+++ b/install
@@ -1,9 +1,158 @@
-#! /bin/sh
+#!/usr/bin/env bash
+#
+# bootstrap installs things.
 
-if [ ! -d "~/.ssh" ]; then
-  `mkdir ~/.ssh`
-fi
-for f in `ls -1A .ssh/`; do rm -f ~/.ssh/$f; ln -fs ~/.dotfiles/.ssh/$f ~/.ssh/$f; done
-for f in `ls -1A | egrep '^\.' | egrep -v '(^\.git$)|(^\.ssh$)'`; do rm -f ~/$f; ln -fs ~/.dotfiles/$f ~/$f; done
-echo 'Changing shell to zsh (Ctrl+C to finish)'
-chsh -s /bin/zsh
+declare -A hosts
+hosts[mentobook]="all book"
+#hosts[some-hostname]="all otherdir"
+hostname=$(hostname)
+
+DOTFILES_ROOT=$(pwd -P)
+
+set -e
+
+echo ''
+
+info () {
+  printf "\r  [ \033[00;34m..\033[0m ] $1\n"
+}
+
+user () {
+  printf "\r  [ \033[0;33m??\033[0m ] $1\n"
+}
+
+success () {
+  printf "\r\033[2K  [ \033[00;32mOK\033[0m ] $1\n"
+}
+
+fail () {
+  printf "\r\033[2K  [\033[0;31mFAIL\033[0m] $1\n"
+  echo ''
+  exit
+}
+
+link_file () {
+  local src=$1 dst=$2
+
+  local overwrite= backup= skip=
+  local action=
+
+  if [ -f "$dst" -o -d "$dst" -o -L "$dst" ]
+  then
+
+    if [ "$overwrite_all" == "false" ] && [ "$backup_all" == "false" ] && [ "$skip_all" == "false" ]
+    then
+
+      local currentSrc="$(readlink $dst)"
+
+      if [ "$currentSrc" == "$src" ]
+      then
+
+        skip=true;
+
+      else
+
+        user "File already exists: $dst, what do you want to do?\n\
+        [s]kip, [S]kip all, [o]verwrite, [O]verwrite all, [b]ackup, [B]ackup all?"
+        read -n 1 action
+
+        case "$action" in
+          o )
+            overwrite=true;;
+          O )
+            overwrite_all=true;;
+          b )
+            backup=true;;
+          B )
+            backup_all=true;;
+          s )
+            skip=true;;
+          S )
+            skip_all=true;;
+          * )
+            ;;
+        esac
+
+      fi
+
+    fi
+
+    overwrite=${overwrite:-$overwrite_all}
+    backup=${backup:-$backup_all}
+    skip=${skip:-$skip_all}
+
+    if [ "$overwrite" == "true" ]
+    then
+      rm -rf "$dst"
+      success "removed $dst"
+    fi
+
+    if [ "$backup" == "true" ]
+    then
+      mv "$dst" "${dst}.backup"
+      success "moved $dst to ${dst}.backup"
+    fi
+
+    if [ "$skip" == "true" ]
+    then
+      success "skipped $src"
+    fi
+  fi
+
+  if [ "$skip" != "true" ]  # "false" or empty
+  then
+    mkdir -p $(dirname $dst)
+    ln -s "$1" "$2"
+    success "linked $1 to $2"
+  fi
+}
+
+install_dotfiles () {
+  info 'installing dotfiles'
+
+  local overwrite_all=false backup_all=false skip_all=false
+  if test "${hosts[$hostname]+isset}"; then
+    for dirs in ${hosts[$hostname]}; do
+      for dir in ${dirs[@]}; do
+        cycle_dirs $dir
+      done;
+    done
+  else
+    cycle_dirs "all"
+  fi
+
+}
+
+cycle_dirs () {
+  dir=$1
+  # echo "$dir"
+  for src in $(find -H "$DOTFILES_ROOT/$dir" -type f); do
+    dst="$HOME/$(realpath --relative-to=$DOTFILES_ROOT/$dir ${src})"
+    # echo "[$DOTFILES_ROOT/$dir]: $src -> $dst"
+    link_file "$src" "$dst"
+  done;
+}
+
+bootstrap () {
+  if [ -d $HOME/.oh-my-zsh ]; then
+    info "Updating Oh My ZSH"
+    p=$(pwd)
+    cd $HOME/.oh-my-zsh
+    pulltxt=$(git pull)
+    info "$pulltxt"
+    cd $p
+  else
+    info "Cloning Oh My ZSH"
+    git clone https://github.com/robbyrussell/oh-my-zsh.git $HOME/.oh-my-zsh
+  fi
+
+  if [ `basename $SHELL` != "zsh" ]; then
+    chsh -s $(which zsh)
+  fi
+}
+
+install_dotfiles
+bootstrap
+
+echo ''
+echo '  All installed!'
